/*
MySQL Data Transfer
Source Host: localhost
Source Database: emulator
Target Host: localhost
Target Database: emulator
Date: 28.02.2010 13:23:46
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for characters
-- ----------------------------
DROP TABLE IF EXISTS `characters`;
CREATE TABLE `characters` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(20) NOT NULL,
  `name` varchar(45) NOT NULL,
  `chartype` int(10) unsigned NOT NULL DEFAULT '1907',
  `volume` int(10) unsigned NOT NULL DEFAULT '22',
  `level` int(10) unsigned NOT NULL DEFAULT '1',
  `strength` int(10) unsigned NOT NULL DEFAULT '20',
  `intelligence` int(10) unsigned NOT NULL DEFAULT '20',
  `attribute` int(10) unsigned NOT NULL DEFAULT '0',
  `hp` int(10) unsigned NOT NULL DEFAULT '200',
  `mp` int(10) unsigned NOT NULL DEFAULT '200',
  `s_hp` int(10) unsigned NOT NULL DEFAULT '200',
  `s_mp` int(10) unsigned NOT NULL DEFAULT '200',
  `gold` int(10) unsigned NOT NULL DEFAULT '0',
  `experience` int(10) unsigned NOT NULL DEFAULT '0',
  `sp` int(10) unsigned NOT NULL DEFAULT '0',
  `gm` int(1) NOT NULL DEFAULT '0',
  `xsect` int(10) unsigned NOT NULL DEFAULT '168',
  `ysect` int(10) unsigned NOT NULL DEFAULT '98',
  `xpos` int(10) unsigned NOT NULL DEFAULT '978',
  `ypos` int(10) unsigned NOT NULL DEFAULT '1097',
  `zpos` int(10) unsigned NOT NULL DEFAULT '40',
  `min_phyatk` int(10) unsigned NOT NULL DEFAULT '6',
  `max_phyatk` int(10) unsigned NOT NULL DEFAULT '9',
  `min_magatk` int(10) unsigned NOT NULL DEFAULT '6',
  `max_magatk` int(10) unsigned NOT NULL DEFAULT '10',
  `phydef` int(10) unsigned NOT NULL DEFAULT '3',
  `magdef` int(10) unsigned NOT NULL DEFAULT '6',
  `hit` int(10) unsigned NOT NULL DEFAULT '11',
  `parry` int(10) unsigned NOT NULL DEFAULT '11',
  `walkspeed` int(10) unsigned NOT NULL DEFAULT '16',
  `runspeed` int(10) unsigned NOT NULL DEFAULT '50',
  `berserkspeed` int(10) unsigned NOT NULL DEFAULT '100',
  `berserkbar` int(10) NOT NULL DEFAULT '0',
  `skillpointbar` int(10) NOT NULL DEFAULT '0',
  `berserking` int(1) NOT NULL DEFAULT '0',
  `pvp` int(10) unsigned NOT NULL DEFAULT '255',
  `maxitemslot` int(3) NOT NULL DEFAULT '45',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for items
-- ----------------------------
DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `itemnumber` varchar(10) DEFAULT NULL,
  `itemid` int(10) unsigned NOT NULL DEFAULT '0',
  `owner` varchar(15) NOT NULL,
  `plusvalue` int(10) unsigned NOT NULL DEFAULT '0',
  `slot` int(10) unsigned NOT NULL,
  `type` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'CH = 0, ETC = 1',
  `quantity` int(10) unsigned NOT NULL DEFAULT '1',
  `durability` int(10) unsigned NOT NULL DEFAULT '30',
  `BlueAmount` int(10) NOT NULL DEFAULT '0',
  `blue1` int(10) NOT NULL DEFAULT '0',
  `blue1amount` int(10) NOT NULL DEFAULT '0',
  `blue2` int(10) NOT NULL DEFAULT '0',
  `blue2amount` int(10) NOT NULL DEFAULT '0',
  `blue3` int(10) NOT NULL DEFAULT '0',
  `blue3amount` int(10) NOT NULL DEFAULT '0',
  `blue4` int(10) NOT NULL DEFAULT '0',
  `blue4amount` int(10) NOT NULL DEFAULT '0',
  `blue5` int(10) NOT NULL DEFAULT '0',
  `blue5amount` int(10) NOT NULL DEFAULT '0',
  `blue6` int(10) NOT NULL DEFAULT '0',
  `blue6amount` int(10) NOT NULL DEFAULT '0',
  `blue7` int(10) NOT NULL DEFAULT '0',
  `blue7amount` int(10) NOT NULL DEFAULT '0',
  `blue8` int(10) NOT NULL DEFAULT '0',
  `blue8amount` int(10) NOT NULL DEFAULT '0',
  `blue9` int(10) NOT NULL DEFAULT '0',
  `blue9amount` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=691 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for mastery
-- ----------------------------
DROP TABLE IF EXISTS `mastery`;
CREATE TABLE `mastery` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `owner` varchar(15) DEFAULT NULL,
  `mastery` int(10) DEFAULT NULL,
  `level` int(10) DEFAULT NULL,
  `mastery_row` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=114 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for news
-- ----------------------------
DROP TABLE IF EXISTS `news`;
CREATE TABLE `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `head` varchar(30) DEFAULT NULL,
  `text` varchar(250) DEFAULT NULL,
  `day` int(2) DEFAULT NULL,
  `month` int(2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for server
-- ----------------------------
DROP TABLE IF EXISTS `server`;
CREATE TABLE `server` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `users_current` int(10) unsigned NOT NULL DEFAULT '0',
  `users_max` int(10) unsigned NOT NULL DEFAULT '500',
  `state` int(10) unsigned NOT NULL DEFAULT '1',
  `ip` varchar(45) NOT NULL,
  `port` int(10) unsigned NOT NULL DEFAULT '15000',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for skills
-- ----------------------------
DROP TABLE IF EXISTS `skills`;
CREATE TABLE `skills` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `owner` varchar(10) NOT NULL,
  `AmountSkill` int(10) unsigned NOT NULL DEFAULT '0',
  `Skill1` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill2` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill3` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill4` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill5` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill6` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill7` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill8` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill9` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill10` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill11` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill12` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill13` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill14` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill15` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill16` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill17` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill18` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill19` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill20` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill21` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill22` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill23` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill24` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill25` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill26` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill27` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill28` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill29` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill30` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill31` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill32` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill33` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill34` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill35` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill36` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill37` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill38` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill39` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill40` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill41` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill42` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill43` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill44` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill45` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill46` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill47` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill48` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill49` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill50` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill51` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill52` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill53` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill54` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill55` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill56` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill57` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill58` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill59` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill60` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill61` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill62` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill63` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill64` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill65` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill66` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill67` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill68` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill69` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill70` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill71` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill72` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill73` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill74` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill75` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill76` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill77` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill78` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill79` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill80` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill81` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill82` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill83` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill84` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill85` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill86` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill87` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill88` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill89` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill90` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill91` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill92` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill93` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill94` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill95` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill96` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill97` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill98` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill99` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill100` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill101` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill102` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill103` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill104` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill105` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill106` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill107` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill108` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill109` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill110` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill111` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill112` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill113` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill114` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill115` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill116` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill117` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill118` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill119` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill120` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill121` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill122` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill123` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill124` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill125` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill126` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill127` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill128` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill129` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill130` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill131` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill132` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill133` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill134` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill135` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill136` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill137` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill138` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill139` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill140` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill141` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill142` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill143` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill144` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill145` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill146` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill147` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill148` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill149` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill150` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill151` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill152` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill153` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill154` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill155` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill156` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill157` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill158` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill159` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill160` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill161` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill162` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill163` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill164` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill165` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill166` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill167` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill168` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill169` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill170` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill171` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill172` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill173` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill174` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill175` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill176` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill177` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill178` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill179` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill180` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill181` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill182` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill183` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill184` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill185` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill186` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill187` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill188` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill189` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill190` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill191` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill192` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill193` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill194` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill195` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill196` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill197` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill198` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill199` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill200` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill201` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill202` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill203` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill204` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill205` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill206` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill207` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill208` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill209` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill210` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill211` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill212` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill213` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill214` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill215` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill216` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill217` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill218` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill219` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill220` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill221` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill222` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill223` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill224` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill225` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill226` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill227` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill228` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill229` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill230` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill231` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill232` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill233` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill234` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill235` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill236` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill237` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill238` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill239` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill240` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill241` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill242` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill243` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill244` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill245` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill246` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill247` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill248` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill249` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill250` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill251` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill252` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill253` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill254` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill255` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill256` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill257` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill258` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill259` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill260` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill261` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill262` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill263` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill264` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill265` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill266` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill267` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill268` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill269` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill270` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill271` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill272` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill273` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill274` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill275` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill276` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill277` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill278` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill279` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill280` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill281` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill282` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill283` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill284` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill285` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill286` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill287` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill288` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill289` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill290` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill291` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill292` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill293` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill294` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill295` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill296` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill297` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill298` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill299` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill300` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill301` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill302` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill303` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill304` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill305` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill306` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill307` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill308` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill309` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill310` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill311` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill312` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill313` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill314` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill315` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill316` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill317` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill318` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill319` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill320` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill321` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill322` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill323` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill324` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill325` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill326` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill327` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill328` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill329` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill330` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill331` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill332` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill333` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill334` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill335` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill336` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill337` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill338` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill339` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill340` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill341` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill342` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill343` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill344` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill345` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill346` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill347` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill348` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill349` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill350` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill351` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill352` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill353` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill354` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill355` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill356` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill357` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill358` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill359` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill360` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill361` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill362` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill363` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill364` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill365` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill366` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill367` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill368` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill369` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill370` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill371` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill372` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill373` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill374` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill375` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill376` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill377` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill378` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill379` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill380` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill381` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill382` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill383` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill384` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill385` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill386` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill387` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill388` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill389` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill390` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill391` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill392` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill393` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill394` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill395` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill396` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill397` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill398` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill399` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill400` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill401` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill402` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill403` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill404` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill405` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill406` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill407` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill408` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill409` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill410` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill411` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill412` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill413` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill414` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill415` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill416` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill417` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill418` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill419` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill420` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill421` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill422` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill423` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill424` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill425` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill426` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill427` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill428` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill429` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill430` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill431` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill432` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill433` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill434` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill435` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill436` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill437` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill438` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill439` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill440` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill441` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill442` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill443` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill444` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill445` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill446` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill447` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill448` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill449` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill450` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill451` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill452` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill453` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill454` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill455` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill456` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill457` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill458` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill459` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill460` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill461` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill462` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill463` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill464` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill465` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill466` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill467` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill468` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill469` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill470` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill471` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill472` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill473` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill474` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill475` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill476` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill477` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill478` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill479` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill480` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill481` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill482` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill483` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill484` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill485` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill486` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill487` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill488` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill489` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill490` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill491` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill492` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill493` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill494` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill495` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill496` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill497` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill498` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill499` int(6) unsigned NOT NULL DEFAULT '0',
  `Skill500` int(6) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL,
  `password` varchar(20) DEFAULT NULL,
  `failed_logins` int(1) DEFAULT '0',
  `online` int(1) DEFAULT '0',
  `char_count` int(1) DEFAULT '0',
  `char_1` varchar(15) DEFAULT '0',
  `char_2` varchar(15) DEFAULT '0',
  `char_3` varchar(15) DEFAULT '0',
  `char_4` varchar(15) DEFAULT '0',
  `banned` int(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `news` VALUES ('5', 'C# Emulator ', 'Open Source Silkroad Emulator', '24', '10');
INSERT INTO `server` VALUES ('0', 'Remote', '0', '100', '0', '127.0.0.1', '15780');
INSERT INTO `server` VALUES ('1', 'Main', '0', '1000', '1', '127.0.0.1', '15780');
